### ISSUE TITLE
[FEATURE REQUEST] add a storageclass parameter to support mapping from storageclass name to nodePath

### ISSUE THREAD

**Issue by yanjunli76** [rancher/local-path-provisioner#101]
Hi there,

We have a case where we mount two type of disks to a node, let's say /mnt/faskdisk, /mnt/slowdisk. We want some pods which are I/O bound use the fast disk and the rest of pods use slow disk. But currently there is no way to configure it in this case. 

We'd like to propose to add a feature to support a storageclass parameter and map from storageclass name to nodePath.

For example, we can customize two storageclass,

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: fast-type
```

and 

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: slow-type
```

The configuration could be
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths": {
                               "fast-type": ["/mnt/fastdisk"],
                               "slow-type": ["/mnt/slowdisk"]
                         }
                }
                ]
        }
```

Then PV with `fast` storageclass will be created under the directory `/mnt/fastdisk`.  The PV with `slow` storageclass will be created under the directory `/mnt/slowdisk`
