### ISSUE TITLE
local-path-provisioner not working on any of my new 2.4.4 Rancher clusters

### ISSUE THREAD

**Issue by adacaccia** [rancher/local-path-provisioner#102]
Hello, here's log from the local-path-provisioner startup:

> kubectl -n local-path-storage logs -f -l app=local-path-provisioner
> time="2020-07-02T11:04:46Z" level=debug msg="Applied config: {\"nodePathMap\":[{\"node\":\"DEFAULT_PATH_FOR_NON_LISTED_NODES\",\"paths\":[\"/mnt/ocfs2/local-path-provisioner\"]}]}" 
> time="2020-07-02T11:04:46Z" level=debug msg="Provisioner started" 
> I0702 11:04:46.139190       1 leaderelection.go:242] attempting to acquire leader lease  local-path-storage/rancher.io-local-path...
> I0702 11:05:29.345216       1 leaderelection.go:252] successfully acquired lease local-path-storage/rancher.io-local-path
> I0702 11:05:29.345423       1 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"local-path-storage", Name:"rancher.io-local-path", UID:"ce6452a4-d435-47de-a54c-76e30eeb32a6", APIVersion:"v1", ResourceVersion:"895442", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' local-path-provisioner-54f4dd9777-vncwf_79257c3f-0586-4515-b92a-7fe04c93be6c became leader
> I0702 11:05:29.345449       1 controller.go:773] Starting provisioner controller rancher.io/local-path_local-path-provisioner-54f4dd9777-vncwf_79257c3f-0586-4515-b92a-7fe04c93be6c!
> I0702 11:05:29.445621       1 controller.go:822] Started provisioner controller rancher.io/local-path_local-path-provisioner-54f4dd9777-vncwf_79257c3f-0586-4515-b92a-7fe04c93be6c!
> 

So it seems it has started well, but... nothing happens after that!
Example POD I'm trying to deploy:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-pvc
  namespace: rtm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx-rtm
  namespace: rtm
  labels:
    app: emqx-rtm
spec:
[...]
  template:
    spec:
      containers:
      [...]
        volumeMounts:
        - mountPath: "/opt/emqx/data/mnesia"
          name: emqx-data
      volumes:
      - name: emqx-data
        persistentVolumeClaim:
          claimName: emqx-pvc
```

No PV is created, so PODs will fail to start and enter LoopBack.
Since the installation manifest leaves the "local-path-provisioner" namespace unassigned to any Rancher project, I've also tried to move it to the "System' project, or to my own project, always restarting it afterwards, but nothing has changed in any of these tests.
Please advise: as I've got an Oracle OCFS2 Multi-Read/Write block volume already setup, mounted and shared between all of my nodes, local-pat-provision would provide me a perfect fit...
