### ISSUE TITLE
error retrieving resource lock local-path-storage/rancher.io-local-path

### ISSUE THREAD

**Issue by Antonyab** [rancher/local-path-provisioner#104]
Hello,

I am using the local path provisionner as mentioned. 

It worked and the local volume persistent storage is created locally on the nodes where the pods are deployed.

After a while, I tried to create a new pvc and I detected that the local path storage pod is showing an error that is repeating each 2 seconds :

E0624 12:05:54.771144 1 leaderelection.go:331] error retrieving resource lock local-path-storage/rancher.io-local-path: endpoints “rancher.io-local-path” is forbidden: User “system:serviceaccount:local-path-storage:local-path-provisioner-service-account” cannot get resource “endpoints” in API group “” in the namespace "local-path-storage"

If I try to bind a new pvc that I created with a pod, the local persistent volume is not created. But it is mentioned that it is bount when I list pv and pvc. 

Anyone can help me fix this issue ?

Thank you in advance.

Regards,
Antony

**Comment by yasker** [comment]
@Antonyab It seems you didn't apply the RBAC rule correctly. Can you try to reapply the following part of [yaml](https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml)? 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints", "persistentvolumes", "pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
- kind: ServiceAccount
  name: local-path-provisioner-service-account
  namespace: local-path-storage
```
