### ISSUE TITLE
Can provisioner directly use the configured mount path instead of creating subfolders?

### ISSUE THREAD

**Issue by makeloffve** [rancher/local-path-provisioner#132]
### background:
- We use the PVC created by local-path-provisioner as Kafka storage. In order to improve performance, Kafka recommends mounting multiple disks. Here is our storage configuration and kafka statefulset startup configuration:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config-kafka
  namespace: itoa
data:
  config.json: |-
        {
                "nodePathMap":[
                        {"node1":  "/mnt/disk-simulators/kafka"}
                ]
        }
  setup: |-
        #!/bin/sh
        path=$1
        mkdir -m 0777 -p ${path}
  teardown: |-
        #!/bin/sh
        path=$1
        rm -rf ${path}
```

```yaml

...
            command:
          - sh
          - -c
          - "exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties  --override broker.id=${HOSTNAME##*-} \
                  --override listeners=PLAINTEXT://0.0.0.0:6667 \
                  --override advertised.listeners=PLAINTEXT://${NODEPORT_HOST_IP}:$((30091 + ${HOSTNAME##*-}))  \
                  --override zookeeper.connect=${ZOOKEEPER_CONNECT} \
                  --override log.dirs= /mnt/disk-simulators/kafka/1, /mnt/disk-simulators/kafka/2, /mnt/disk-simulators/kafka/3 \
...
...
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path-kafka
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 500Gi
```

- Our disks are respectively mounted under `/mnt/disk-simulators/kafka/1`, `/mnt/disk-simulators/kafka/2`, `/mnt/disk-simulators/kafka/3`

- We found that local-path-provisioner can only create subfolders starting with pvc under /mnt/disk-simulators/kafka, like: `/mnt/disk-simulators/kafka/pvc-1499f261-8460-4adc-bb9f-4d9e7181585e_itoa_data-itoa-kafka-statefulset-1`, `/mnt/disk-simulators/kafka/pvc-b97ae2d4-98b5-43d5-80d3-dd4730f75a4f_itoa_data-itoa-kafka-statefulset-3` and cannot make good use of the disks we mounted separately

#### There are new issues worth discussing here:
 The path configured by local-path-provisioner currently seems to be shared by all PVCs. If the PVC created by local-path-provisioner is used as storage for es, kafka, and db at the same time, Probably these storage software runs on the same disk
