### ISSUE TITLE
prometheus in rancher 2.5: failed to provision volume with StorageClass "local-path": claim.Spec.Selector is not supported

### ISSUE THREAD

**Issue by mamiu** [rancher/local-path-provisioner#142]
In Rancher 2.5 (which was released yesterday) the installation of monitoring fails because Prometheus creates a PVC with a `selector` property. Here's the current state of the PVC (with all irrelevant fields removed):

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k3d-demo-server-0
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    prometheus: rancher-monitoring-prometheus
    manager: k3s
    operation: Update
  name: prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0
  namespace: cattle-monitoring-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector: {}
  storageClassName: local-path
  volumeMode: Filesystem
status:
  phase: Pending
```

The log of the `local-path-provisioner` pod show this error message:

```log
[...] failed to provision volume with StorageClass "local-path": claim.Spec.Selector is not supported [...]
```

I found that issue #56, but it doesn't resolve this error. And editing the PVC doesn't work because of this restriction: `Forbidden: spec is immutable after creation except resources.requests for bound claims`.

**Comment by hwk42** [comment]
I also encountered the same problem when install alluxio in k3s.
`  Warning  ProvisioningFailed    2m56s (x11 over 84m)  rancher.io/local-path_local-path-provisioner-5d7b5579c7-v44hc_82108aeb-d956-42e2-9c31-7ff185df52ad  failed to provision volume with StorageClass "local-path": claim.Spec.Selector is not supported`

**Comment by mamiu** [comment]
Interestingly, I get exactly the same error with longhorn. Doesn't seem to be a local-path-provisioner specific problem. However, I also got this error message on more applications than just Prometheus. As a workaround I simply deleted the following lines from the PVC before deploying:

```yaml
  selector:
    matchExpressions: []
    matchLabels: {}
```
