### ISSUE TITLE
Documentation: Multiple Local Path Provisioners in the same cluster

### ISSUE THREAD

**Issue by japsu** [rancher/local-path-provisioner#152]
Suppose there are two kinds of drives in the K8s nodes, "fast" (SSD) and "big" (HDD). Suppose I want to create two storage classes, one of which provisions volumes on the "fast" drives and one on the "big" drives. Please document how to achieve this.

From #80 I gather this is possible by deploying two instances of local-path-provisioner that are backed by directories on the fast and big drives respectively. But how do I specify in the storage class specification which instance of LPP to use? Do I have to change the `provisioner` value? How do I tell LPP which value of the `provisioner` field in SC to respond to?

**Comment by japsu** [comment]
Apparently something like this (Helm values.yaml)

```yaml
storageClass:
  name: local-path-big
  provisionerName: con2.fi/local-path-big

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /mnt/big
```
