### ISSUE TITLE
How to push node affinity labels from storage class

### ISSUE THREAD

**Issue by deveshk0** [rancher/local-path-provisioner#185]
Currently If you define a node with empty path `[ ]`, pod get scheduled to that node though provision cannot provision volume there but pod is stuck,

is there any way we can push cutom label for scheduling from storage class ?

**Comment by ErikLundJensen** [comment]
See #163  which kind of the same issue. Cloud we close this issue as a duplicate?

**Comment by deveshk0** [comment]
I managed to this via allowedTopologies in storage class - 

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast-storage
provisioner: rancher.io/fast-storage
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: storageclass/fast-storage
        values:
         - true
```
