### ISSUE TITLE
Support Volume Expansion

### ISSUE THREAD

**Issue by ekristen** [rancher/local-path-provisioner#190]
Since local-path-provisioner does not enforce capacity limitations, then I see no reason to throw errors in the event that someone changes the spec.capacity settings.

The following PR implements a partial fix that does away with the error messages. The remaining fix would be to simply update the PVC status to match the spec in a no-op function since it doesn't actually enforce or have to provision space.

Again since there is zero enforcement I see no reason to not simply set the setting that allows for volume expansion. 

The error being `only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize`

PR - https://github.com/rancher/local-path-provisioner/pull/189

Other issues 
- https://github.com/rancher/local-path-provisioner/issues/107
- https://github.com/rancher/local-path-provisioner/issues/18

**Comment by ekristen** [comment]
Is there any reason to not do this? If the provisioner isn't actually enforcing or check data sizes, why not allow the size to be changed so it doesn't throw an error?

**Comment by michaelandrepearce** [comment]
Any update on this?

**Comment by quato666** [comment]
By the way - xfs quota works great, because at the pod/container level it returns proper size values with df :)

**Comment by derekbit** [comment]
@quato666

Thanks for the feedback.
I don't have much time for this project at the moment, so the development and update will be slow.
If you're interested in this feature. Any contribution is welcomed. Thank you in advance.

**Comment by laurivosandi** [comment]
I am also interested in this

**Comment by jessebot** [comment]
It looks like #350 may no longer be in development, so if others are familiar enough to tackle this, it may be a good time to submit a PR. This feature would be incredibly useful.

**Comment by fs185143** [comment]
Any progress on this? Currently if I do the following:
- Add `allowVolumeExpansion: true` to the `local-path` `StorageClass` 
- Create a VM with a `local-path` disk, e.g.,
```yaml
  - metadata:
      name: os-vm-basic-disk
      namespace: os-example
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 80Gi
```
- Patch `os-vm-basic-disk` `PersistentVolumeClaim` and increase the value, e.g.,
```yaml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
```

Then the PVC just gets stuck in this state

> Warning  ExternalExpanding      7m3s                volume_expand                                                                                       waiting for an external controller to expand this PVC
