### ISSUE TITLE
Current local-path-provisioner deploy example not working with latest k3d

### ISSUE THREAD

**Issue by DylanGuedes** [rancher/local-path-provisioner#211]
Hello,
the current deployment example (located [here](https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml)) isn't fully working with the latest k3d versions because of a role-binding mismatch.

Steps to reproduce:
1. Create a new k3d cluster: k3d cluster create mycluster --kubeconfig-update-default=false
2. Apply the cluster config with `export KUBECONFIG=$(k3d kubeconfig write mycluster)`
3. Apply the local-path-provisioner deployment: `kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml`

Experienced error:
A local-path-provisioner pod in the `kube-system` namespace will run into crashloop-backoff. This is the log error for the pod:
```
time="2021-10-04T19:08:57Z" level=fatal msg="Error starting daemon: invalid empty flag helper-pod-file and it also does not exist at ConfigMap kube-system/local-path-config with err: configmaps \"local-path-config\" is forbidden: User \"system:serviceacc
ount:kube-system:local-path-provisioner-service-account\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""
```

Kubectl auth output:
```
kubectl auth can-i get configmaps --as=system:serviceaccount:kube-system:local-path-provisioner-service-account -n kube-system
no
```

Quick work-around:
Create a new role-binding/service-account just for the kube-system namespace:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: kube-system
```
