### ISSUE TITLE
use provsioner w/o specifying pvc

### ISSUE THREAD

**Issue by aintbrokedontfix** [rancher/local-path-provisioner#255]
Is there an example of how to use the provisioner in a PodTemplate? For example using NFS storage in a pod template could look like this:

```yaml
     template:
      spec:
       volumes:
       - name: volv
         nfs:
           server: nfs.example.org
           path: /nfs/path
```
