### ISSUE TITLE
use worker-threads have error

### ISSUE THREAD

**Issue by ChenJhua** [rancher/local-path-provisioner#262]
when i use
```
      containers:
        - name: local-path-provisioner
          image: proxy.harbor/local-xdr/rancher/local-path-provisioner:v0.0.22
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --worker-threads=10
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --worker-threads
            - 10

kubectl apply -f local-path-storage.yaml 
namespace/local-storage created
serviceaccount/local-path-provisioner-service-account created
clusterrole.rbac.authorization.k8s.io/local-path-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/local-path-provisioner-bind created
configmap/local-path-config created
Error from server (BadRequest): error when creating "local-path-storage.yaml": Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field Container.spec.template.spec.containers.command of type string
```
when i use string
```
      containers:
        - name: local-path-provisioner
          image: proxy.harbor/local-xdr/rancher/local-path-provisioner:v0.0.22
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --worker-threads=10
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --worker-threads
            - "10"

kubectl logs -f -n local-storage local-path-provisioner-74878b57dc-slcvg
panic: Usage error, please check your command

goroutine 1 [running]:
main.onUsageError(0xc00013e780, 0x175b600, 0xc00012a610, 0xc000114100, 0x0, 0x0)
	/go/src/github.com/rancher/local-path-provisioner/main.go:55 +0x68
github.com/urfave/cli.(*App).Run(0xc00012c340, 0xc00018c000, 0x8, 0x8, 0x175b600, 0xc00012a610)
	/go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/app.go:203 +0x46c
main.main()
	/go/src/github.com/rancher/local-path-provisioner/main.go:308 +0x2c8
```

i retry helm install use deploy chart, have `cannot unmarshal number` error

kubernetes: 1.23.9
docker:18.09.0

**Comment by ChenJhua** [comment]
@dittos can you tell me what is the problem

**Comment by derekbit** [comment]
@ChenJhua 
Sorry for late reply
This line is incorrect and not necessary.
```
- --worker-threads=10
```


The expamle should work
```
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.22
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --worker-threads
            - "10"
```
