### ISSUE TITLE
Can I deploy the local-path-provisioner pod to multiple nodes?

### ISSUE THREAD

**Issue by HanHoRang31** [rancher/local-path-provisioner#305]
It's a feature question. I want to set up a local volume only on specific nodes(ex. node1, node2, node3)
Can I simply deploy the local-path-provisioner pods on the nodes that will use the local volume using toleration and nodeselector?

**Comment by Sensei-CHO** [comment]
+1

**Comment by artarik** [comment]
You can do it in your service via tolerations and nodeSelection.
pod local-path-provisioner deploying via deployment so it can be run as single replica

**Comment by Sensei-CHO** [comment]
Do you have an example to give us ?

**Comment by artarik** [comment]
sure
my storageClass has name _openebs-lvm-vghdd_
**tolerations**
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vghdd-pvc
spec:
  storageClassName: openebs-lvm-vghdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtkpi-pod
  labels:
    app: mtkpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtkpi
  template:
    metadata:
      labels:
        app: mtkpi
    spec:
      containers:
        - resources:
          name: mtkpi-pod
          image: r0binak/mtkpi:v1
          ports:
          - containerPort: 7681
          securityContext:
            readOnlyRootFilesystem: true
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data_hdd
              name: pvc-data-hdd
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/lvmhdd
          operator: Exists
      volumes:
        - name: pvc-data-hdd
          persistentVolumeClaim:
            claimName: vghdd-pvc
```
**nodeselector**
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vghdd-pvc
spec:
  storageClassName: openebs-lvm-vghdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtkpi-pod
  labels:
    app: mtkpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtkpi
  template:
    metadata:
      labels:
        app: mtkpi
    spec:
      containers:
        - resources:
          name: mtkpi-pod
          image: r0binak/mtkpi:v1
          ports:
          - containerPort: 7681
          securityContext:
            readOnlyRootFilesystem: true
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data_hdd
              name: pvc-data-hdd
      nodeSelector:
        disktype: hdd
      volumes:
        - name: pvc-data-hdd
          persistentVolumeClaim:
            claimName: vghdd-pvc
```
