### ISSUE TITLE
Helm: Allow to configure several storageclass

### ISSUE THREAD

**Issue by vsellier** [rancher/local-path-provisioner#316]
With the release of #306, it's now possible to use different storageclass to route the data to different directories. It's very useful :medal_sports:  but it's not yet possible to use in the helm chart.

WDYT to update it to support this kind of configuration:
```
## For creating the StorageClass automatically:
storageClasses:
  create: true

  ## Set a provisioner name. If unset, a name will be generated.
  # provisionerName: rancher.io/local-path

  classes:
    # The default storageclass with random path selection
    # For retro-compatibility with version < 0..0.24
    local-path:
      ## Set StorageClass as the default StorageClass
      ## Ignored if storageClass.create is false
      defaultClass: false
      ## ReclaimPolicy field of the class, which can be either Delete or Retain
      reclaimPolicy: Delete

      ## The path where to store the volumes
      ## Must exist in nodePathMap, if not specified, the path would be chosen
      ## randomly when provisioning.
      # nodePath: /my/path
```
