### ISSUE TITLE
Helm: specify the type of volume you want the provisioner to create

### ISSUE THREAD

**Issue by bsctl** [rancher/local-path-provisioner#320]
To specify (at global level) the type of volume you want the provisioner to create, you can add the following annotation to the StorageClass:

```yaml
annotations:
  defaultVolumeType: <local or hostPath>
```

I would be nice to set this annotation:

```yaml
## For creating the StorageClass automatically:
storageClass:
  create: true

  ## Set a provisioner name. If unset, a name will be generated.
  # provisionerName: rancher.io/local-path

  ## Set StorageClass as the default StorageClass
  ## Ignored if storageClass.create is false
  defaultClass: false

  ## Set default VolumeType
  ## Ignored if storageClass.create is false
  #defaultVolumeType: <local or hostPath>

  ## Set a StorageClass name
  ## Ignored if storageClass.create is false
  name: local-path

  ## ReclaimPolicy field of the class, which can be either Delete or Retain
  reclaimPolicy: Delete
```

 If this make sense to you, I will provide a PR. Thanks!
