### ISSUE TITLE
busybox 1.36.1 Illegal option -a

### ISSUE THREAD

**Issue by githubcdr** [rancher/local-path-provisioner#366]
Hi,

Not sure if this is a regression or a change in busybox, but I noticed this error when lpp tries to create a volume

```
Illegal option -a
```

```yaml
  - args:
    - -p
    - /var/local/local-path-provisioner/pvc-9c3c30f8-20b5-429d-9c69-71e7b8b7f54b_minio_minio
    - -s
    - "549755813888"
    - -m
    - Filesystem
    - -a
    - create
    command:
    - /bin/sh
    - /script/setup
  image: busybox
```

Using v0.0.25
