### ISSUE TITLE
Pod with nodeName hangs while waiting for PVC to be provisioned

### ISSUE THREAD

**Issue by enrichman** [rancher/local-path-provisioner#383]
Creating a pod without the `nodeName` being specified hangs the provisioning of the PVC, because of the `WaitForFirstConsumer` volume binding mode.

## Test

1) Simple Pod and PVC works :+1: 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - image: "debian:stable-slim"
    name: sample
    command: ["/bin/bash", "-c", "--"]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: vol
        mountPath: /tmp/test
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: myclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: "10M"
```

2) Specifying the `nodeName` where the Pod should be scheduled hangs :red_circle: 

PVC log:
> waiting for first consumer to be created before binding

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  nodeName: k3d-test-server-0
  containers:
  - image: "debian:stable-slim"
    name: sample
    command: ["/bin/bash", "-c", "--"]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: vol
        mountPath: /tmp/test
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: myclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: "10M"
```

## Fixes

Two possible fixes:
1) set the same node in the PVC with the `volume.kubernetes.io/selected-node` annotation
2) change the storageclass `volumeBindingMode` to `Immediate`

## References

I think [this](https://github.com/rancher/local-path-provisioner/issues/332#issuecomment-1641499696) is related, so not sure if this is an actual problem/bug, or not.
