### ISSUE TITLE
StorageClass annotations defaultVolumeType not work

### ISSUE THREAD

**Issue by lanss315425** [rancher/local-path-provisioner#390]
hi ,I am not working properly using the Storage Class annotations defaultVolume Type，Normally, there is a volumeType: local in the annotations of PVC. The following image shows my Storage Class.
<img width="1489" alt="image" src="https://github.com/rancher/local-path-provisioner/assets/19217018/092564c7-bc87-4239-803a-9516dbc5711a">

this is my pvc :
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-test-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
 kubectl describe pvc nginx-test-pvc：
<img width="1476" alt="image" src="https://github.com/rancher/local-path-provisioner/assets/19217018/17db3046-4d1e-4a03-90d6-6e34ed9c54a0">

<img width="828" alt="image" src="https://github.com/rancher/local-path-provisioner/assets/19217018/4289d842-24d8-4c2c-947f-0c2a26412209">
