### ISSUE TITLE
Helm chart contains duplicate labels

### ISSUE THREAD

**Issue by runningman84** [rancher/local-path-provisioner#392]
````
➜  local-path-provisioner git:(master) helm template .
####
---
# Source: local-path-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-local-path-provisioner
  namespace: default
  labels:
    app.kubernetes.io/name: local-path-provisioner
    helm.sh/chart: local-path-provisioner-0.0.25-dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.0.25-dev"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local-path-provisioner
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-path-provisioner
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: local-path-provisioner
        helm.sh/chart: local-path-provisioner-0.0.25-dev
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "v0.0.25-dev"
        app.kubernetes.io/managed-by: Helm
    spec:
####
````

The duplicate lines are a problem for flux which denies installing the chart
````
│     Message:               Helm install failed for release kube-system/local-path-provisioner with chart local-path-provisioner@0.0.25-dev: error while running post render on files: map[string │
│ ]interface {}(nil): yaml: unmarshal errors:                                                                                                                                                      
│   line 26: mapping key "app.kubernetes.io/name" already defined at line 24                                                                                                                       
│   line 28: mapping key "app.kubernetes.io/instance" already defined at line 25     
````
