### ISSUE TITLE
Not working for subPath

### ISSUE THREAD

**Issue by AmreeshTyagi** [rancher/local-path-provisioner#4]
Thanks for providing this provisioner. I am setting up MySQL HA using Kubernetes [Stateful example](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/). 

I have tried this provisioner, but it is creating dynamic PV & mounting also but not in DEFAULT provided directory, but on this path `/var/lib/kubelet/pods/82d24112-fc50-11e8-90e7-005056b146f6/volume-subpaths`.

I found that it is happeing if I use `subPath`, otherwise it works well.

Any idea, how can I resolve this issue?

**Comment by steav** [comment]
Yes, same for me.

**Working without subpath** (findmnt):
`|-/vol1    datastore[/local-path-pvc/pvc-b499d69f-2252-11e9-8fc6-14dda9d41a28]            zfs     rw,relatime,xattr,noacl`

**Problem using subpath**:
`|-/vol1    overlay[/mnt/datastore/local-path-pvc/pvc-c0de97a5-2254-11e9-8fc6-14dda9d41a28/subdir1]     overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/`

Creating the directory tree before deployment does not help.

**Comment by yasker** [comment]
@AmreeshTyagi @steav Can you elaborate the problem? Or provide a yaml for expected behavior? Does the container work?

**Comment by khassel** [comment]
same for me. Seems that the volume-mount does not work with a subpath.
The `pod.yaml` example works as expected, but if you add a subpath it doesn't work.
Executing `kubectl exec volume-test -- sh -c "echo local-path-test > /data/test"` will write a test-file somewhere in `/var/lib/kubelet/pods/...` but not in the directory provided by the pvc `local-path-pvc`

**Comment by khassel** [comment]
yes, exactly.

**Comment by DrMurx** [comment]
I came across the same issue:

1) Create a single node Rancher cluster
2) Install `local-path-provisioner` storage class
3) Enable cluster level monitoring built into RKE, and enable persistent storage for Prometheus on the `local-path` storage class

**Comment by khassel** [comment]
@yasker Could you reproduce this subPath issue? Can we expect a solution?

**Comment by yasker** [comment]
@khassel You're right, I able to reproduce the issue now.

It seems due to https://github.com/kubernetes/kubernetes/issues/61456 . Seems it's a problem with containized kubelet. If you're using RKE, we have an issue tracking it with Rancher: https://github.com/rancher/rancher/issues/14836

I've also tried using `LocalVolume` instead of `HostPath`, but it doesn't work for RKE as well. Seems not much I can do at the moment except waiting for the RKE fix.

**Comment by khassel** [comment]
@yasker Thanks for this info.

**Comment by AntonSmolkov** [comment]
Hi!
Workaround: 
```
kubectl patch statefulset prometheus-cluster-monitoring --type='json' --namespace=cattle-prometheus -p '
- op: remove
  path: "/spec/template/spec/containers/0/volumeMounts/1/subPath"
'
```

Source: https://vividcode.io/prometheus-operator-persistence-with-rancher-local-path-provisioner/

**Comment by disaster37** [comment]
Hi,
I have tested to patch as explain it. But after patch it, kubernetes redeploy statefullset and so overwrite the patched, ...
So it doesn't work.

Have you any idea ?

**Comment by attrib** [comment]
@yasker https://github.com/kubernetes/kubernetes/issues/61456 and https://github.com/rancher/rancher/issues/14836 got closed, but from my understanding there it seems to be not really fixed? Or is this helpful and this issue could be fixed in the future?

**Comment by immanuelfodor** [comment]
FYI, we've spend half a day to debug why our Prometheus is filling up the /var/lib/docker folder when provisioned by Rancher Monitoring V2.5, and found this issue and also https://github.com/rancher/rancher/issues/29149 

```yaml
# prometheus volume set by the operator:

     - mountPath: /prometheus                                                                                                                                                                                                              
       name: prometheus-rancher-monitoring-prometheus-db                                                                                                                                                                                   
       subPath: prometheus-db
```

An update of the Prometheus Operator should help in this case, the fix was validated on the linked ticket 23 days ago.
