### ISSUE TITLE
securityContext fsGroup has no effect

### ISSUE THREAD

**Issue by h0tbird** [rancher/local-path-provisioner#41]
My setup:
```
kind version
v0.5.1
kind create cluster
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```

**Test 1**: _emptyDir_
```
cat << EOF | k apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: security-context-works
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
EOF
```
it works (2000):
```
kubectl exec -it security-context-works -- ls -la /data/
total 12
drwxr-xr-x    3 root     root          4096 Aug 28 12:12 .
drwxr-xr-x    1 root     root          4096 Aug 28 12:12 ..
drwxrwsrwx    2 root     2000          4096 Aug 28 12:12 demo
```

**Test 2**: _rancher.io/local-path_
```
cat << EOF | k apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
EOF
```
```
cat << EOF | k apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: security-context-fails
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: data-test
    persistentVolumeClaim:
      claimName: data-test
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: data-test
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
EOF
```

It fails (root):
```
kubectl exec -it security-context-fails -- ls -la /data/
total 12
drwxr-xr-x    3 root     root          4096 Aug 28 12:20 .
drwxr-xr-x    1 root     root          4096 Aug 28 12:20 ..
drwxrwxrwx    2 root     root          4096 Aug 28 12:20 demo
```

Any idea what is causing that? I was expecting the group to be `2000` for the demo directory.
