### ISSUE TITLE
Issue with the helper pod security context being overwritten

### ISSUE THREAD

**Issue by js185692** [rancher/local-path-provisioner#420]
A change made in `v0.0.27` (https://github.com/rancher/local-path-provisioner/pull/402) has introduced an issue where the security context for the helper pod has been hard coded into the provisioner, overwriting any configuration that might be made in the configmap.

```go
helperPod.Spec.Containers[0].SecurityContext = &v1.SecurityContext{
	SELinuxOptions: &v1.SELinuxOptions{
		Level: "s0-s0:c0.c1023",
	},
}
```

It's not clear to me why the above change was needed to be made in the provisioner? It seems to me that the same could have been achieved with the following config;

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
...
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
            seLinuxOptions:
                level: s0-s0:c0.c1023
```
