### ISSUE TITLE
how to limit  storage size?

### ISSUE THREAD

**Issue by loprx** [rancher/local-path-provisioner#471]
This is the YAML for creating POD and PVC.
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
```
I exec this POD and using command `dd if=/dev/zero of=/data/aaa bs=4096 count=1024000` writer file sucess.
But YMAL request  to store as 128Mi.
