### ISSUE TITLE
Dynamic provisioning with node affinity

### ISSUE THREAD

**Issue by az-z** [rancher/local-path-provisioner#477]
Hello,
 I must have been doing something incorrectly, but I can not spot the issue.  My objective is to enable dynamic provisioning based on the node affinity label (local-storage=enabled) in k3s: I'd like to mount the existing directory (/tmp/blah) from the current single node ( dell5000) into the deployment.

Current state - pod is pending
configuration:
```
kubectl version
Client Version: v1.31.4+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.4+k3s1

kubectl get nodes -o wide
NAME       STATUS   ROLES                  AGE   VERSION        INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION           CONTAINER-RUNTIME
dell5000   Ready    control-plane,master   11d   v1.31.4+k3s1   192.168.1.135   <none>        Fedora Linux 40 (Forty)   6.5.12-100.fc37.x86_64   containerd://1.7.23-k3s2

```
I shortened the info for the node:

```
kubectl describe node dell5000
Name:               dell5000
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=dell5000
                    kubernetes.io/os=linux
                    local-storage=enabled
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.1.135
                    flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"36:ca:cf:dc:c5:b3"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.1.135
                    k3s.io/hostname: dell5000
                    k3s.io/internal-ip: 192.168.1.135
                    k3s.io/node-args: ["server"]
                    k3s.io/node-config-hash: MLFMUCBMRVINLJJKSG32TOUFWB4CN55GMSNY25AZPESQXZCYRN2A====
                    k3s.io/node-env: {}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 27 Jan 2025 14:21:39 -0500
Taints:             <none>
Unschedulable:      false
<cut here>

```

StorageClass, configmap and PVC:
```

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-class
  annotations:
    defaultVolumeType: local
provisioner: rancher.io/local-path
parameters:
  fsType: ext4
reclaimPolicy: Retain # Or Delete
volumeBindingMode: WaitForFirstConsumer # Important!

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vault-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  storageClassName: local-storage-class

---
 
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
##  namespace: local-path-storage
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt/local-path-provisioner"]
                },
                {
                        "node":"yasker-lp-dev1",
                        "paths":["/opt/local-path-provisioner", "/data1"]
                },
                {
                        "node":"dell5000",
                        "paths":["/tmp/blah"]
                }
                ]
        }
  setup: |-
        #!/bin/sh
        set -eu
        mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
        #!/bin/sh
        set -eu
        rm -rf "$VOL_DIR"
  helperPod.yaml: |-
        apiVersion: v1
        kind: Pod
        metadata:
          name: helper-pod
        spec:
          priorityClassName: system-node-critical
          tolerations:
            - key: node.kubernetes.io/disk-pressure
              operator: Exists
              effect: NoSchedule
          containers:
          - name: helper-pod
            image: busybox
```

Deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: vault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: local-storage
                operator: In
                values:
                - enabled
      containers:
      - image: docker.io/hashicorp/vault
        name: vault
        resources: {}
        ports:
        - containerPort: 8200
        env:
          - name: VAULT_ADDR
            value: "http://0.0.0.0:8200"
        command: ["/bin/sh", "-c"]
        args: ["vault server -config=/vault/config/vault.hcl"]
        #DO NOT mount into /vault container will crash without any explanation.
        volumeMounts:
          - name: scripts
            mountPath: /vault/scripts
          - name: config
            mountPath: /vault/config
          - name: file
            mountPath: /vault/file
          - name: logs
            mountPath: /vault/logs
        # Probes use hardcoded VAULT_ADDR in their scripts.
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-c","/vault/scripts/init.sh > /vault/logs/init.log"]
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "/vault/scripts/health_check.sh > /vault/logs/health.log 2>&1"
      volumes:
        - name: scripts
          hostPath:
            path: /home/az/Work/repo/infra/playground/vault/scripts
        - name: config
          persistentVolumeClaim: 
            claimName: pvc-vault-config
          #hostPath:
          #  path: /home/az/Work/repo/infra/playground/vault/config
        - name: file
          hostPath:
            path: /home/az/Work/repo/infra/playground/vault/file
        - name: logs
          hostPath:
            path: /home/az/Work/repo/infra/playground/vault/logs
status: {}
```

As you can see, I'm attempting to switch from ```hostPath``` to claims ("pvc-vault-config").

The Logs:

```
kubectl get pods -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
vault-app-6cbd5d968-bhkkq   0/1     Pending   0          47m   <none>   <none>   <none>           <none>


kubectl  get sc
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  11d
local-storage-class    rancher.io/local-path   Retain          WaitForFirstConsumer   false                  41m

 kubectl  get pvc
NAME                      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          VOLUMEATTRIBUTESCLASS   AGE
data-mysql-1738171510-0   Bound     pvc-6fb83cf3-6a33-43e5-a9fd-d4e746c5a95a   8Gi        RWO            local-path            <unset>                 9d
pvc-vault-config          Pending                                                                        local-storage-class   <unset>                 45m

kubectl  get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                             STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-6fb83cf3-6a33-43e5-a9fd-d4e746c5a95a   8Gi        RWO            Delete           Bound    default/data-mysql-1738171510-0   local-path     <unset>                          9d

```

So it looks like pod is waiting for PVC, and PVC -> StorageClass is waiting for the pod ...

I appreciate your help.

P.S. I do not have DaemonSet running.
