### ISSUE TITLE
helperPod tolerates all taints set on a node by default by using extremely permissive toleration

### ISSUE THREAD

**Issue by sbocinec** [rancher/local-path-provisioner#487]
The provisioner [always adds](https://github.com/rancher/local-path-provisioner/blob/8219f6cde014ed2f7290d1a94b9b6ec2adc11408/provisioner.go#L669) extremely permissive `- operator: Exists` [toleration](https://github.com/rancher/local-path-provisioner/blob/master/provisioner.go#L603-L606) to the helperPod spec.tolerations. This causes the helperPod tolerates all/any tolerations set on a node, so it's impossible to prevent it from scheduling.

This defeats the purpose of setting tolerations through the configMap `helperPod.yaml` as it has no practical effect.

Example:
1. Using the following `helperPod.yaml` config:
```
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: public.ecr.aws/docker/library/busybox:1.36-glibc@sha256:e046063223f7eaafbfbc026aa3954d9a31b9f1053ba5db04a4f1fdc97abd8963
      tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
        effect: NoSchedule
```

the provisioner creates a helperPod with the following spec.tolerations set:
```
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - operator: Exists
```
