### ISSUE TITLE
Add the ability to set security contexts for helper pod

### ISSUE THREAD

**Issue by AbhishekBandarupalle** [rancher/local-path-provisioner#493]
For the helm chart values, readme describes that configmap that defines the helper pod can be defined as user values, but the template for the configmap does not read anything other than the image name and its tag.

I would want to use the helm chart with a helper pod that can understand selinux contexts and also set the selinux contexts on the directory created using the setup.sh script.

Eg: - it would be easier if the template could be updated as readme defines all the variables.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
data:
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
      namespace: local-path-storage
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: helper-pod
          image: registry.access.redhat.com/ubi9/ubi:9.5
          imagePullPolicy: IfNotPresent
          resources:
            {}
          securityContext:
            privileged: true
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
    chcon -R -t container_file_t "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
```
