### ISSUE TITLE
Security context not respected

### ISSUE THREAD

**Issue by unguiculus** [rancher/local-path-provisioner#7]
I'm trying to use `local-path-provisioner` with [kind](https://github.com/kubernetes-sigs/kind). While it seems to generally work with multi-node clusters, security contexts are not respected. Volumes are always mounted with `root` as group. Here's a simple example that demonstrates this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: local-path-test
  labels:
    app.kubernetes.io/name: local-path-test
spec:
  containers:
    - name: test
      image: busybox
      command:
        - /config/test.sh
      volumeMounts:
        - name: test
          mountPath: /test
        - name: config
          mountPath: /config
  securityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  terminationGracePeriodSeconds: 0
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: local-path-test
    - name: config
      configMap:
        name: local-path-test
        defaultMode: 0555

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-path-test
  labels:
    app.kubernetes.io/name: local-path-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-test
  labels:
    app.kubernetes.io/name: local-path-test
data:
  test.sh: |
    #!/bin/sh

    ls -al /test

    echo 'Hello from local-path-test'
    cp /config/text.txt /test/test.txt
    touch /test/foo

  text.txt: |
    some test content
```

Here's the log from the container:

```
total 4
drwxr-xr-x    2 root     root            40 Feb 22 09:50 .
drwxr-xr-x    1 root     root          4096 Feb 22 09:50 ..
Hello from local-path-test
cp: can't create '/test/test.txt': Permission denied
touch: /test/foo: Permission denied
```

As can be seen, the mounted volume has `root` as group instead of `1000` as specified by the security context. I also installed `local-path-provisioner` on Docker4Mac. The result is the same, so it is not a `kind` issue. Using the default storage class on Docker4Mac, it works as expected.
