### ISSUE TITLE
Customizing Provisioner Name (e.g. to mock kubernetes.io/aws-ebs plugin)

### ISSUE THREAD

**Issue by aimannajjar** [rancher/local-path-provisioner#72]
Hello - 
We have a use case where we would like to _mimic_ the existence of AWS volume plugin on k3s, by using something like local storage path. 

I noticed in the [source code](https://github.com/rancher/local-path-provisioner/blob/da26716a7d28f4830fa877597fb9c0e2d8cbc73c/main.go#L60-L64) that the Provisioner Name is supports a flag with the name `PROVISIONER_NAME`. 

I've deployed the following local-path-provisioner deployment at k3s and it seems to be starting up successfully, the pod logs are showing correct name as well.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ebs-mock-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-ebs-mock-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aws-ebs-mock-provisioner
    spec:
      containers:
      - command:
        - local-path-provisioner
        - start
        - --config
        - /etc/config/config.json
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PROVISIONER_NAME
          value: kubernetes.io/aws-ebs
        image: rancher/local-path-provisioner:v0.0.12
        imagePullPolicy: IfNotPresent
        name: local-path-provisioner
        volumeMounts:
        - mountPath: /etc/config/
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: local-path-provisioner-service-account
      serviceAccountName: local-path-provisioner-service-account
      volumes:
      - configMap:
          defaultMode: 420
          name: ebs-local-path-config
        name: config-volume
```

However, it doesn't seem that k3s is recognizing the plugin. PVCs are stlil showing the following event:
```
  Warning  ProvisioningFailed    104s (x182 over 46m)  persistentvolume-controller  no volume plugin matched
``` 

I am not sure if my understanding of the PROVISIONER_NAME flag is correct, or if this is a bug, or whether I need to take additional steps to register the volume with k3s using the name `kubernetes.io/aws-ebs`. 

I would greatly appreciate any pointers!

Thank you
